### ISSUE TITLE
fix failing homomorphic addition test

### ISSUE THREAD

**Issue by jacksonwalters** [lattice-based-cryptography/module-lwe#2]
currently homomorphic addition test fails. appears coefficients are forced to be 0 or 1 in decrypt.rs.

**Comment by jacksonwalters** [comment]
made some minor changes like passing params and seed to encrypt, and generating the random ephemeral keys inside the encrypt function (rather than passing as parameters). it looks like it's encoded in binary, but the addition is then taking place component-wise mod 2, which isn't right. so like [1,0,1] + [1,0,0] --> [0,0,1], which isn't right if I want to encode 5 and 1 in binary.

**Comment by tjaysilver** [comment]
[1,0,1] + [1,0,0] --> [0,0,1] is correct actually I think, since this is adding polynomials mod 2:
this would correspond to (1+x^2)+1 = 2+x^2 = x^2 mod 2.

**Comment by jacksonwalters** [comment]
I thought maybe so, especially if we're working over \Z/q\Z and q is a power of 2. however, I tried powers of 3 and got the same behavior. we do want dec(enc(2)+enc(3)) = 5. I haven't looked at the ciphertext yet while debugging. I feel like encoding 5 as [1,0,1,0,...,0] isn't quite right somehow. how does it know how to carry?
